apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: scaffoldops-dev

resources:
  - minio-credentials-secret.yaml
  - minio-pvc.yaml
  - minio-deployment.yaml
  - minio-service.yaml
  - minio-create-bucket-job.yaml
