apiVersion: v1
kind: Service
metadata:
  name: keycloak-dev
  namespace: security
spec:
  type: ClusterIP
  selector:
    app: keycloak-dev
  ports:
    - name: http
      port: 8080
      targetPort: 8080
