apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: security

resources:
  - keycloak-dev-admin-secret.yaml
  - keycloak-dev-db-secret.yaml
  - keycloak-dev-deployment.yaml
  - keycloak-dev-service.yaml
  - keycloak-pre-admin-secret.yaml
  - keycloak-pre-db-secret.yaml
  - keycloak-pre-deployment.yaml
  - keycloak-pre-service.yaml
